In [1]:
import numpy as np

## DataTypes & Attributes 

In [2]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0, 3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6,],
                  [7,8,9]],
                   [[10,11,12],
                      [13,14,15],
                        [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(4,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(4, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Creat a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

##  2. Creating NumPy arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 2, 4, 6, 9],
       [4, 7, 9, 9, 9],
       [8, 9, 5, 3, 6]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((5, 3))

In [26]:
random_array_2.shape

(5, 3)

In [27]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.86633117, 0.3252383 , 0.04713479],
       [0.92270601, 0.46111614, 0.71255716],
       [0.10709999, 0.72331477, 0.17395921],
       [0.06520634, 0.09995128, 0.77746906],
       [0.19814868, 0.13707175, 0.65761213]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [29]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [30]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1

array([1, 2, 3, 4])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

1

In [35]:
a2[0]

array([1. , 2. , 3.3])

In [36]:
a3.shape

(2, 3, 3)

In [37]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a2[1]

array([4. , 5. , 6.5])

In [39]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [40]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [41]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [42]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [43]:
# Get the first 4 numbers of the inner most arrays

a4[:, :, :, :2]

array([[[[3, 5],
         [5, 0],
         [9, 6],
         [3, 3]],

        [[1, 0],
         [7, 9],
         [7, 7],
         [3, 1]],

        [[4, 3],
         [9, 1],
         [2, 5],
         [9, 9]]],


       [[[3, 0],
         [7, 2],
         [6, 6],
         [7, 1]],

        [[9, 9],
         [6, 8],
         [6, 1],
         [9, 8]],

        [[7, 5],
         [8, 1],
         [3, 7],
         [7, 5]]]])

## 4. Manipulating & comparing arrays

### Artihmetic 

In [44]:
a1

array([1, 2, 3, 4])

In [45]:
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

In [46]:
a1 + ones

array([2., 3., 4., 5.])

In [47]:
a1 - ones

array([0., 1., 2., 3.])

In [48]:
a1 * ones

array([1., 2., 3., 4.])

In [49]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [50]:
#How to reshape numpy array
a1 * a2

ValueError: operands could not be broadcast together with shapes (4,) (2,3) 

In [51]:
a1 / ones

array([1., 2., 3., 4.])

In [52]:
# Floor division removes the decimals (rounds down)

In [53]:
a2 **2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [54]:
a1 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [55]:
np.square(a1)

array([ 1,  4,  9, 16], dtype=int32)

In [56]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [57]:
np.add(a1, ones)

array([2., 3., 4., 5.])

In [58]:
a1 % 2

array([1, 0, 1, 0], dtype=int32)

In [59]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [60]:
np.mod(a1, 2)

array([1, 0, 1, 0], dtype=int32)

In [61]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [62]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

## Aggregation

Aggregation = performing the same operation on a number of things

In [63]:
listy_list = [1,2,3]
type(listy_list)

list

In [64]:
sum(listy_list)

6

In [65]:
type(a1)

numpy.ndarray

In [66]:
sum(a1)

10

In [67]:
np.sum(a1)

10

In [68]:
# Use Python's methods on Python datatypes and  Numpy's merhods on NumPy arrays

In [69]:
massive_array = np.random.random(100000)

In [70]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [71]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

8.01 ms ± 198 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
32 µs ± 67.3 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [72]:
np.max(a2)

6.5

In [73]:
np.std(a2)

1.8226964152656422

In [74]:
np.var(a2)

3.3222222222222224

In [75]:
np.sqrt(np.var(a2))

1.8226964152656422