In [1]:
import numpy as np

## DataTypes & Attributes 

In [2]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0, 3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6,],
                  [7,8,9]],
                   [[10,11,12],
                      [13,14,15],
                        [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(4,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(4, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Creat a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

##  2. Creating NumPy arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 8, 4, 8, 3],
       [4, 8, 4, 8, 8],
       [3, 9, 8, 3, 5]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random((5, 3))

In [29]:
random_array_2.shape

(5, 3)

In [30]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.67046515, 0.45593149, 0.37280555],
       [0.95262766, 0.03444101, 0.78952116],
       [0.71671204, 0.22918435, 0.41961356],
       [0.65146503, 0.12208694, 0.67804025],
       [0.60654153, 0.67922603, 0.31956328]])

In [31]:
# Pseudo-random numbers
np.random.seed()