In [1]:
import numpy as np

## DataTypes & Attributes 

In [2]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0, 3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6,],
                  [7,8,9]],
                   [[10,11,12],
                      [13,14,15],
                        [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(4,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(4, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Creat a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

##  2. Creating NumPy arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 8, 4, 8, 3],
       [4, 8, 4, 8, 8],
       [3, 9, 8, 3, 5]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random((5, 3))

In [29]:
random_array_2.shape

(5, 3)

In [32]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.32962184, 0.04882551, 0.88194645],
       [0.37266543, 0.52244435, 0.12167692],
       [0.86277577, 0.70837633, 0.90770117],
       [0.63904836, 0.76833246, 0.12780045],
       [0.12454627, 0.72383887, 0.98797582]])

In [53]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [54]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [57]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a1

array([1, 2, 3, 4])

In [59]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [60]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [61]:
a1[0]

1

In [62]:
a2[0]

array([1. , 2. , 3.3])

In [63]:
a3.shape

(2, 3, 3)

In [64]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])