In [1]:
import numpy as np

## DataTypes & Attributes 

In [2]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0, 3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6,],
                  [7,8,9]],
                   [[10,11,12],
                      [13,14,15],
                        [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(4,)