In [2]:
import numpy as np

## DataTypes & Attributes 

In [3]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0, 3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6,],
                  [7,8,9]],
                   [[10,11,12],
                      [13,14,15],
                        [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(4,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(4, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Creat a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

##  2. Creating NumPy arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 4, 3, 6, 7],
       [3, 3, 4, 2, 9],
       [6, 5, 3, 1, 6]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5, 3))

In [27]:
random_array_2.shape

(5, 3)

In [28]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.61151248, 0.32674986, 0.18771819],
       [0.33928356, 0.61009426, 0.10937856],
       [0.49892835, 0.50687156, 0.36567838],
       [0.29870198, 0.73369814, 0.10077642],
       [0.46237811, 0.42002066, 0.78280473]])

In [29]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [30]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [31]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a1

array([1, 2, 3, 4])

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a1[0]

1

In [36]:
a2[0]

array([1. , 2. , 3.3])

In [37]:
a3.shape

(2, 3, 3)

In [38]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a2[1]

array([4. , 5. , 6.5])

In [40]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [42]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [43]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [44]:
# Get the first 4 numbers of the inner most arrays

a4[:, :, :, :2]

array([[[[3, 5],
         [5, 0],
         [9, 6],
         [3, 3]],

        [[1, 0],
         [7, 9],
         [7, 7],
         [3, 1]],

        [[4, 3],
         [9, 1],
         [2, 5],
         [9, 9]]],


       [[[3, 0],
         [7, 2],
         [6, 6],
         [7, 1]],

        [[9, 9],
         [6, 8],
         [6, 1],
         [9, 8]],

        [[7, 5],
         [8, 1],
         [3, 7],
         [7, 5]]]])

## 4. Manipulating & comparing arrays

### Artihmetic 

In [45]:
a1

array([1, 2, 3, 4])

In [47]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [48]:
a1 + ones

ValueError: operands could not be broadcast together with shapes (4,) (3,) 